[tools]
pnpm = "9.15.1"
go = "1.23.3"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", build = "postgres" }

[env]
DATABASE_URI = "postgres://way:way@postgres-127.0.0.1.nip.io:5432/way?sslmode=disable"
DATABASE_HOST = "postgres-127.0.0.1.nip.io"
DATABASE_PORT = 5432
DATABASE_USER = "way"
DATABASE_PASSWORD = "way"
DATABASE_NAME = "way"
DATABASE_SSLMODE = "disable"
ENVIRONMENT_TYPE = "development"
WEB_HOST = "localhost"
WEB_PORT = 3000
NODE_ENV = "development"
LOG_LEVEL = "debug"
MISE_GO_SET_GOPATH = true
_.path = ['./node_modules/.bin']

[tasks.serve-backend]
run = "nx serve @way/backend"

[tasks.build]
run = "nx run-many -t build"

[tasks.test]
run = "nx run-many -t test"

[tasks.lint]
run = "nx run-many -t lint"

[tasks.database-migrate]
run = "nx run @way/backend-database:prisma-migrate"

[tasks.database-generate]
run = "nx run @way/backend-database:prisma-generate"

[tasks.database-status]
run = "nx run @way/backend-database:prisma-status"

[tasks.database-deploy]
run = "nx run @way/backend-database:prisma-deploy"

[tasks.docker-start]
run = "docker-compose up -d"

[tasks.docker-stop]
run = "docker-compose down"

[tasks.docker-logs]
run = "docker-compose logs -f"

[tasks.migrate-create]
run = "migrate -database '$DATABASE_URI' create -dir=db/migrations -seq -ext=sql"

[tasks.migrate-up]
run = "migrate -database '$DATABASE_URI' -path db/migrations up"
